<?php

/**
 * @file
 * Module file for feeds_multinode_processor.module.
 */
/**
 * Implements hook_feeds_plugins().
 */
function feeds_multinode_processor_feeds_plugins(){
  $info = array();
  $info['FeedsMultiNodeProcessor'] = array(
    'name' => 'Multi-node processor',
    'description' => 'Create and update nodes from multiple content types.',
    'handler' => array(
      'parent' => 'FeedsNodeProcessor',
      'class' => 'FeedsMultiNodeProcessor',
      'file' => 'FeedsMultiNodeProcessor.inc',
      'path' => drupal_get_path('module', 'feeds_multinode_processor')
    )
  );
  return $info;
}

/**
 * Implements hook_schema_alter().
 */
function feeds_multinode_processor_schema_alter(&$schema){
  $schema['feeds_item']['fields']['bundle'] = array(
    'type' => 'varchar',
    'length' => 32,
    'not null' => FALSE,
    'default' => ''
  );
}

function feeds_multinode_processor_menu_alter(&$items){
  $items['import/%feeds_importer/template']['page callback'] = 'feeds_multinode_processor_download_template';
  $items['import/%feeds_importer/template']['file'] = 'feeds_multinode_processor.template.inc';
  $items['import/%feeds_importer/template']['file path'] = drupal_get_path('module', 'feeds_multinode_processor');
  
  $items['import/%feeds_importer/populated-template']['page callback'] = 'feeds_multinode_processor_download_populated_template';
  $items['import/%feeds_importer/populated-template']['file'] = 'feeds_multinode_processor.template.inc';
  $items['import/%feeds_importer/populated-template']['file path'] = drupal_get_path('module', 'feeds_multinode_processor');
  
  $items['feeds_multinode_processor/getfile']['page callback'] = 'feeds_multinode_processor_get_populated_template';
  $items['feeds_multinode_processor/getfile']['file'] = 'feeds_multinode_processor.template.inc';
  $items['feeds_multinode_processor/getfile']['file path'] = drupal_get_path('module', 'feeds_multinode_processor');
  
}

/**
 * Implements hook_permission().
 */
function feeds_multinode_processor_permission(){
  return array(
      'feeds multinode processor allow download' => array(
          'title' => t('Feeds multinode processor allow download'),
          'description' => t('Allow the user to download all of the site\'s data in an Excel template.')
      )
  );
}


/**
 * Generate an entry in the feeds_item table that can be used by the populated
 * Excel template (or any other import).
 */
function feeds_multinode_processor_get_or_generate_feeds_item_entry($entity_type, $entity_id, $id, $guid = FALSE){
  $row = db_select('feeds_item', 'f')->fields('f')->condition('entity_type', $entity_type)->condition('entity_id', $entity_id)->execute()->fetchAssoc();
  if($row){
    return $row;
  }else{
    if(!$guid){
      // Generate an appropriate guid
      $guid = microtime(TRUE);
    }
    $record = array(
        'entity_type' => $entity_type,
        'entity_id' => $entity_id,
        'id' => $id,
        'feed_nid' => 0,
        'imported' => time(),
        'url' => '',
        'guid' => $guid,
        'hash' => 'd41d8cd98f00b204e9800998ecf8427e'
    );
    drupal_write_record('feeds_item', $record);
    return $record;
  }
}