<?php

/**
 * Simplenews module
 *
 * Implements hook_scratchpads_default_permissions().
 */
function simplenews_scratchpads_default_permissions(){
  return array(
      'maintainer' => array(
          'administer newsletters',
          'administer simplenews subscriptions',
          'administer simplenews settings',
          'send newsletter',
          'administer scs'
      ),
      'anonymous user' => array(
          'subscribe to newsletters'
      )
  );
}